zuul:
  routes:
    user:
      url: http://auth.imooc.com:9090
    token:
      url: http://auth.imooc.com:9090
    order:
      url: http://order.imooc.com:9080
  sensitive-headers: #no sensative headers. all headers including header will be forwarded.
server:  port: 9070
