spring:
  application:    name: user-api
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-security?characterEncoding=utf8
    username: dbuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    generate-ddl: true
    show-sql: true
server:  ssl:
    key-store: classpath:jojo.key
    key-store-password: 123456
    key-password: 123456