spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-security?characterEncoding=utf8
    username: dbuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090